# Copyright (c) 2024-2025, NVIDIA CORPORATION.

{% set pyproject_data = load_file_data("pyproject.toml") %}
{% set version = pyproject_data["project"]["version"] %}

package:
  name: rapids-build-backend
  version: {{ version }}

source:
  path: ../../..

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.9
    - conda-verify
    {% for r in pyproject_data["build-system"]["requires"] %}
    - {{ r }}
    {% endfor %}
  run:
    {% for r in pyproject_data["project"]["dependencies"] %}
    - {{ r }}
    {% endfor %}

about:
  home: {{ pyproject_data["project"]["urls"]["Homepage"] }}
  license: {{ pyproject_data["project"]["license"] }}
  license_file: {{ pyproject_data["tool"]["setuptools"]["license-files"][0] }}
  summary: {{ pyproject_data["project"]["description"] }}
  description: |
    This package contains the PEP 517 build backend adapter used by all of
    RAPIDS. It does not directly perform builds, but rather performs various
    RAPIDS-specific metadata manipulations before calling down to another build
    backend like setuptools to finish the job.
  dev_url: {{ pyproject_data["project"]["urls"]["Source"] }}
  doc_url: {{ pyproject_data["project"]["urls"]["Documentation"] }}
