name: build

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  conda-build:
    uses: ./.github/workflows/checks.yaml
    with:
      publish: true
    secrets: inherit
