name: build

on:
  push:
    tags:
      - "v*.*.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  run-checks:
    uses: ./.github/workflows/checks-and-builds.yaml
    with:
      build_type: branch
      # RAPIDS tooling assumes that builds for 'build_type=branch' come from a file 'build.yaml'.
      # This adjusts that expectation to match the way this repo works.
      build_workflow_name: "build-tag.yaml"
      publish: true
    secrets: inherit
