name: build

on:
  push:
    branches:
      - "main"
    tags:
      - v[0-9][0-9].[0-9][0-9].[0-9][0-9]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  conda-build:
    needs: check-style
    runs-on: ubuntu-latest
    container:
      image: rapidsai/ci-conda:latest
    steps:
      - uses: actions/checkout@v3
      - name: Python build
        run: "ci/build_python.sh true"
  wheel-build:
    needs: check-style
    runs-on: ubuntu-latest
    container:
      image: "rapidsai/ci-wheel:latest"
    steps:
      - name: checkout code repo
        uses: actions/checkout@v3
      - name: Build and repair the wheel
        run: "./ci/build_wheel.sh true"
